services:
    database:
        container_name: influxdb
        image: influxdb
        restart: no
        env_file: ./.env
        ports:
            - "8086:8086"
        volumes:
            - ./data/influxdb-data:/var/lib/influxdb2
            - ./data/influxdb-config:/etc/influxdb2

    lfs_vcu:
        container_name: lfs-vcu
        build: .
        command: "npm run prod"
        env_file: ./.env
        privileged: true
        restart: no
        depends_on:
            database:
                condition: service_started
        ports:
            - "5432:5432"
            - "6000:6000"
        volumes:
            - ./data:/lfs-vcu/data
            - ./:/lfs-vcu/source
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: "host"
        devices:
            - "/dev/serial0:/dev/ttyAMA0"
            - "/dev/ttyAMA2:/dev/ttyAMA2"
            - "/dev/ttyAMA5:/dev/ttyAMA5"
