services:
    database:
        container_name: influxdb
        image: influxdb
        restart: no
        env_file: ./main/.env
        ports:
            - "8086:8086"
        volumes:
            - ./data-prod-4/influxdb-data:/var/lib/influxdb2
            - ./data-prod-4/influxdb-config:/etc/influxdb2

    lfs_vcu_main:
        container_name: lfs-vcu-main
        build: main
        command: "npm run prod"
        env_file: ./main/.env
        privileged: true
        restart: no
        network_mode: host
        depends_on:
            mavlink_router:
                condition: service_started
        volumes:
            - ./data-prod-3:/lfs-vcu/data
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mavlink_router:
        container_name: mavlink-router
        build: mavlink-router
        command: "npm run prod"
        env_file: ./mavlink-router/.env
        privileged: true
        restart: no
        depends_on:
            database:
                condition: service_started
        network_mode: host
        volumes:
            - ./data-prod-3:/mavlink-router/data
        devices:
            - "/dev/ttyUSB0:/dev/ttyAMA2"
