services:
    database:
        container_name: influxdb
        image: influxdb
        restart: always
        networks:
            - lfs-network
        env_file: ./.env
        ports:
            - "8086:8086"
        volumes:
            - ./data/influxdb-data:/var/lib/influxdb2
            - ./data/influxdb-config:/etc/influxdb2
        healthcheck:
            test: [ "CMD", "influx", "ping" ]
            timeout: 5s
            interval: 5s
            retries: 100

    lfs_vcu:
        container_name: lfs-vcu
        build: .
        command: "npm run prod"
        env_file: ./.env
        privileged: true
        depends_on:
            database:
                condition: service_healthy
        networks:
            - lfs-network
        ports:
            - "5432:5432"
            - "6000:6000"
        volumes:
            - ./data:/lfs-vcu/data
        extra_hosts:
            - "host.docker.internal:host-gateway"
        devices:
            - "/dev/serial0:/dev/ttyAMA0"
            - "/dev/ttyAMA2:/dev/ttyAMA2"
            - "/dev/ttyAMA5:/dev/ttyAMA5"

networks:
    lfs-network:
        driver: bridge


