services:
    database:
        container_name: influxdb
        image: influxdb
        restart: no
        env_file: ./main/.env
        ports:
            - "8086:8086"
        volumes:
            - ./data/influxdb-data:/var/lib/influxdb2
            - ./data/influxdb-config:/etc/influxdb2

    lfs_vcu_main:
        container_name: lfs-vcu-main
        build: main
        command: "npm run prod"
        env_file: ./main/.env
        privileged: true
        restart: no
        depends_on:
            database:
                condition: service_started
            mavlink_router:
                condition: service_started
        volumes:
            - ./data:/lfs-vcu/data
            - ./:/lfs-vcu/source
        network_mode: "host"
        devices:
            - "/dev/ttyAMA5:/dev/ttyAMA5"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mavlink_router:
        container_name: mavlink-router
        build: mavlink-router
        command: "npm run prod"
        env_file: ./mavlink-router/.env
        privileged: true
        restart: no
        network_mode: "host"
        volumes:
            - ./data:/mavlink-router/data
        devices:
            - "/dev/ttyAMA2:/dev/ttyAMA2"
        extra_hosts:
            - "host.docker.internal:host-gateway"
